## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP

variables: 
  utils_path: "/openebs/e2e-packet/script/utils"

# Setup the kubernetes cluster

packet-cluster:
  image: chandankumar4/packet:v4
  stage: CLUSTER-SETUP 
  script:
    - mkdir -p ~/.ssh && ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
    - echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
    - chmod 755 ./script/packet
    - ./script/packet
  artifacts:
    paths:
      - cluster/

## Setup OpenEBS control plane

openebs-packet-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - packet-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - openebs-packet/

openebs-sc-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - packet-cluster
  script:
   - chmod 775 ./script/provider/setup-sc
   - ./script/provider/setup-sc
  artifacts:
    paths:
      - openebs-packet/


